apiVersion: v1
kind: Service
metadata:
  name: kavita
  namespace: default
spec:
  selector:
    app: kavita
  type: LoadBalancer
  ports:
  - name: kavita
    protocol: TCP
    port: 5000
    targetPort: kavita
