resources:
  - plex
  - jellyfin
  - homarr
  - kavita
  - delugevpn
  - firefox
  - filebrowser
  - filebrowser-downloads
  - calibre
  - pyload
  - immich
  - monitoring
secretGenerator:
  - name: env-secrets
    envs:
      - .env
