apiVersion: v1
kind: Service
metadata:
  name: pyload
  namespace: default
spec:
  selector:
    app: pyload
  type: LoadBalancer
  ports:
  - name: pyload
    protocol: TCP
    port: 8085
    targetPort: pyload
