apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: default
spec:
  selector:
    app: prowlarr
  type: LoadBalancer
  ports:
  - name: prowlarr
    protocol: TCP
    port: 9696
    targetPort: prowlarr
