apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: default
  labels:
    app: plex
spec:
  selector:
    matchLabels:
      app: plex
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container:  plex
      labels:
        app: plex
    spec:
      restartPolicy: Always
      containers:
      - name: plex
        image: lscr.io/linuxserver/plex:latest
        imagePullPolicy: Always
        livenessProbe:
          tcpSocket:
            port: 32400
          initialDelaySeconds: 60
          periodSeconds: 5
        ports:
        - containerPort: 32400
          name: plex
        volumeMounts:
          - name: media
            mountPath: /media
          - name: config
            mountPath: /config
          - name: dri
            mountPath: /dev/dri
        envFrom:
          - configMapRef:
              name: plex
      volumes:
        - name: media
          hostPath:
            path: /mnt/user/Downloads/media
            type: DirectoryOrCreate
        - name: config
          hostPath:
            path: /mnt/user/appdata/plex
            type: DirectoryOrCreate
        - name: dri
          hostPath:
            path: /dev/dri
            type: Directory
