apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
  namespace: default
  labels:
    app: filebrowser
spec:
  selector:
    matchLabels:
      app: filebrowser
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container:  filebrowser
      labels:
        app: filebrowser
    spec:
      restartPolicy: Always
      containers:
      - name: filebrowser
        image: filebrowser/filebrowser:latest
        imagePullPolicy: Always
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 5
        ports:
        - containerPort: 80
          name: filebrowser
        volumeMounts:
          - name: data
            mountPath: /srv
          - name: database
            mountPath: /database
          - name: config
            mountPath: /config
      volumes:
        - name: data
          hostPath:
            path: /mnt/user/Files/filebrowser/srv
            type: DirectoryOrCreate
        - name: database
          hostPath:
            path: /mnt/user/Files/filebrowser/db
            type: DirectoryOrCreate
        - name: config
          hostPath:
            path: /mnt/user/Files/filebrowser/config
            type: DirectoryOrCreate
