apiVersion: v1
kind: Service
metadata:
  name: filebrowser
  namespace: default
spec:
  selector:
    app: filebrowser
  ports:
  - name: filebrowser
    protocol: TCP
    port: 8082
    targetPort: filebrowser
