apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey
  namespace: storage
  labels:
    app: valkey
spec:
  selector:
    matchLabels:
      app: valkey
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: valkey
      labels:
        app: valkey
    spec:
      restartPolicy: Always
      securityContext:
        fsGroup: 1000
      containers:
      - name: valkey
        image: valkey/valkey:bookworm
        imagePullPolicy: Always
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 60
          periodSeconds: 5
        ports:
        - containerPort: 6379
          name: valkey
