apiVersion: v1
kind: Service
metadata:
  name: valkey
  namespace: storage
spec:
  selector:
    app: valkey
  type: ClusterIP
  ports:
  - name: valkey
    protocol: TCP
    port: 6379
    targetPort: valkey
