apiVersion: v1
kind: Service
metadata:
  name: vaultwarden
  namespace: default
spec:
  selector:
    app: vaultwarden
  ports:
  - name: vaultwarden
    protocol: TCP
    port: 8087
    targetPort: vaultwarden
