namespace: monitoring

resources:
  - namespace.yaml

helmCharts:
- name: grafana
  repo: https://grafana.github.io/helm-charts
  releaseName: grafana
  namespace: monitoring
  valuesFile: ./values/grafana.yaml
- name: loki
  repo: https://grafana.github.io/helm-charts
  releaseName: loki
  namespace: monitoring
  valuesFile: ./values/loki.yaml
- name: alloy
  repo: https://grafana.github.io/helm-charts
  releaseName: alloy
  namespace: monitoring
  valuesFile: ./values/alloy.yaml
- name: prometheus
  repo: https://prometheus-community.github.io/helm-charts
  releaseName: kube-prometheus-stack
  namespace: monitoring
  valuesFile: ./values/alloy.yaml
