apiVersion: v1
kind: ConfigMap
metadata:
  name: paperless
  namespace: default
data:
  PUID: "1000"
  PGID: "1000"
  TZ: "Mexico/General"
  PAPERLESS_PORT: "8000"
  PAPERLESS_URL: "https://paperless.pvarber.com"
