apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless
  namespace: default
  labels:
    app: paperless
spec:
  selector:
    matchLabels:
      app: paperless
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container:  paperless
      labels:
        app: paperless
    spec:
      restartPolicy: Always
      securityContext:
        fsGroup: 1000
      containers:
      - name: paperless
        image: ghcr.io/paperless-ngx/paperless-ngx:latest
        imagePullPolicy: Always
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 5
        ports:
        - containerPort: 8000
          name: paperless
        volumeMounts:
          - name: config
            mountPath: /usr/src/paperless/data
          - name: media
            mountPath: /usr/src/paperless/media
        envFrom:
          - configMapRef:
              name: paperless
      - name: paperless-kv
        image: valkey/valkey:bookworm
        imagePullPolicy: Always
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 60
          periodSeconds: 5
        ports:
        - containerPort: 6379
          name: paperless-kv
        volumeMounts:
          - name: kv-data
            mountPath: /data
      volumes:
        - name: config
          hostPath:
            path: /mnt/user/appdata/paperless/app
            type: DirectoryOrCreate
        - name: media
          hostPath:
            path: /mnt/user/appdata/paperless/media
            type: DirectoryOrCreate
        - name: kv-data
          hostPath:
            path: /mnt/user/appdata/paperless/kv
            type: DirectoryOrCreate
