apiVersion: v1
kind: Service
metadata:
  name: paperless
  namespace: default
spec:
  selector:
    app: paperless
  ports:
  - name: paperless
    protocol: TCP
    port: 8000
    targetPort: paperless
