apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cloudflare
  namespace: cert-manager
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cloudflare-account-key
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: env-secrets
            key: CLOUDFLARE_API_TOKEN
