apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare
spec:
  acme:
    email: work@pvarber.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cloudflare-account-key
    solvers:
    - dns01:
        cloudflare:
          email: work@pvarber.com
          apiTokenSecretRef:
            name: cert-secrets
            key: CLOUDFLARE_API_TOKEN
