apiVersion: v1
kind: ConfigMap
metadata:
  name: immich
  namespace: default
data:
  PUID: "1000"
  GUID: "1000"
  UMASK: "022"
  DB_HOSTNAME: "localhost"
  REDIS_HOSTNAME: "localhost"
  IMMICH_PORT: ""
