apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich
  namespace: default
  labels:
    app: immich
spec:
  selector:
    matchLabels:
      app: immich
  replicas: 0
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container:  immich
      labels:
        app: immich
    spec:
      restartPolicy: Always
      containers:
      - name: immich
        image: ghcr.io/imagegenius/immich:noml
        imagePullPolicy: Always
        livenessProbe:
          tcpSocket:
            port: 8086
          initialDelaySeconds: 60
          periodSeconds: 5
        ports:
        - containerPort: 8086
          name: immich
        volumeMounts:
          - name: config
            mountPath: /config
          - name: photos
            mountPath: /photos
          - name: libraries
            mountPath: /libraries
          - name: dri
            mountPath: /dev/dri
            readOnly: true
        envFrom:
          - configMapRef:
              name: immich
        env:
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: env-secrets
                key: IMMICH_DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: env-secrets
                key: IMMICH_DB_PASSWORD
          - name: DB_DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: env-secrets
                key: IMMICH_DB_DB
      - name: immich-db
        image: tensorchord/pgvecto-rs:pg16-v0.2.0
        imagePullPolicy: Always
        livenessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 60
          periodSeconds: 5
        ports:
        - containerPort: 5432
          name: immich-db
        volumeMounts:
          - name: data
            mountPath: /var/lib/postgresql/data
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: env-secrets
                key: IMMICH_DB_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: env-secrets
                key: IMMICH_DB_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: env-secrets
                key: IMMICH_DB_DB
      - name: immich-kv
        image: valkey/valkey:bookworm
        imagePullPolicy: Always
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 60
          periodSeconds: 5
        ports:
        - containerPort: 6379
          name: immich-kv
      volumes:
        - name: config
          hostPath:
            path: /mnt/user/appdata/immich
            type: DirectoryOrCreate
        - name: data
          hostPath:
            path: /mnt/user/appdata/PostgreSQL_Immich
            type: DirectoryOrCreate
        - name: photos
          hostPath:
            path: /mnt/user/Files/immich/photos
            type: DirectoryOrCreate
        - name: libraries
          hostPath:
            path: /mnt/user/Files/filebrowser/srv/
            type: DirectoryOrCreate
        - name: dri
          hostPath:
            path: /dev/dri
            type: Directory
