apiVersion: v1
kind: Service
metadata:
  name: immich
  namespace: default
spec:
  selector:
    app: immich
  type: LoadBalancer
  ports:
  - name: immich
    protocol: TCP
    port: 8086
    targetPort: immich
