apiVersion: v1
kind: Service
metadata:
  name: calibre
  namespace: default
spec:
  selector:
    app: calibre
  type: LoadBalancer
  ports:
  - name: calibre
    protocol: TCP
    port: 8080
    targetPort: calibre
