apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: cloudflare
    traefik.ingress.kubernetes.io/router.middlewares: default-stripprefix@kubernetescrd
  name: homelab
  namespace:
spec:
  rules:
  - http:
      paths:
      - path: /vault
        pathType: Prefix
        backend:
          service:
            name: vaultwarden
            port:
              number: vaultwarden
  tls:
  - hosts:
    - homelab.pvarber.com
    secretName: homelab-cert
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: stripprefix
spec:
  stripPrefix:
    prefixes:
      - /vault
