apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: default
  labels:
    app: jellyfin
spec:
  selector:
    matchLabels:
      app: jellyfin
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container:  jellyfin
      labels:
        app: jellyfin
    spec:
      restartPolicy: Always
      containers:
      - name: jellyfin
        image: lscr.io/linuxserver/jellyfin:latest
        imagePullPolicy: Always
        livenessProbe:
          tcpSocket:
            port: 8096
          initialDelaySeconds: 60
          periodSeconds: 5
        ports:
        - containerPort: 8096
          name: jellyfin
        volumeMounts:
          - name: media
            mountPath: /data
          - name: config
            mountPath: /config
          - name: dri
            mountPath: /dev/dri
        envFrom:
          - configMapRef:
              name: jellyfin
      volumes:
        - name: media
          hostPath:
            path: /mnt/user/Downloads/media
            type: DirectoryOrCreate
        - name: config
          hostPath:
            path: /mnt/user/appdata/jellyfin
            type: DirectoryOrCreate
        - name: dri
          hostPath:
            path: /dev/dri
            type: Directory
