apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: default
spec:
  selector:
    app: jellyfin
  type: LoadBalancer
  ports:
  - name: jellyfin
    protocol: TCP
    port: 8096
    targetPort: jellyfin
