apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser-downloads
  namespace: default
  labels:
    app: filebrowser-downloads
spec:
  selector:
    matchLabels:
      app: filebrowser-downloads
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container:  filebrowser-downloads
      labels:
        app: filebrowser-downloads
    spec:
      restartPolicy: Always
      containers:
      - name: filebrowser-downloads
        image: filebrowser/filebrowser:latest
        imagePullPolicy: Always
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 5
        ports:
        - containerPort: 80
          name: filebrowser-d
        volumeMounts:
          - name: data
            mountPath: /srv
          - name: database
            mountPath: /database
          - name: config
            mountPath: /config
      volumes:
        - name: data
          hostPath:
            path: /mnt/user/Downloads
            type: Directory
        - name: database
          hostPath:
            path: /mnt/user/appdata/filebrowser-downloads/db
            type: DirectoryOrCreate
        - name: config
          hostPath:
            path: /mnt/user/appdata/filebrowser-downloads
            type: DirectoryOrCreate
