apiVersion: v1
kind: Service
metadata:
  name: filebrowser-downloads
  namespace: default
spec:
  selector:
    app: filebrowser-downloads
  type: LoadBalancer
  ports:
  - name: filebrowser-downloads
    protocol: TCP
    port: 8083
    targetPort: filebrowser-d
