apiVersion: apps/v1
kind: Deployment
metadata:
  name: firefox
  namespace: default
  labels:
    app: firefox
spec:
  selector:
    matchLabels:
      app: firefox
  replicas: 0
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container:  firefox
      labels:
        app: firefox
    spec:
      restartPolicy: Always
      containers:
      - name: firefox
        image: lscr.io/linuxserver/firefox:latest
        imagePullPolicy: Always
        livenessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 5
        ports:
        - containerPort: 3000
          name: firefox
        - containerPort: 3001
          name: firefox-https
        volumeMounts:
          - name: config
            mountPath: /config
          - name: shm
            mountPath: /dev/shm
          - name: dri
            mountPath: /dev/dri
            readOnly: true
        envFrom:
          - configMapRef:
              name: firefox
        securityContext:
          privileged: true
      volumes:
        - name: config
          hostPath:
            path: /mnt/user/appdata/firefox-hw
            type: DirectoryOrCreate
        - name: shm
          emptyDir:
            medium: Memory
        - name: dri
          hostPath:
            path: /dev/dri
            type: Directory
