apiVersion: v1
kind: Service
metadata:
  name: firefox
  namespace: default
spec:
  selector:
    app: firefox
  ports:
  - name: firefox
    protocol: TCP
    port: 3030
    targetPort: firefox
  - name: firefox-https
    protocol: TCP
    port: 3031
    targetPort: firefox-https
