repositories:
 - name: grafana
   url: https://grafana.github.io/helm-charts

releases:
- name: grafana
  namespace: grafana
  chart: grafana/grafana
  values:
    - ./values/grafana-values.yaml
- name: loki
  namespace: loki
  chart: grafana/loki
  values:
    - ./values/loki-values.yaml
- name: alloy
  namespace: loki
  chart: grafana/alloy
  values:
    - ./values/alloy-values.yaml
