apiVersion: v1
kind: Service
metadata:
  name: syncthing
  namespace: default
spec:
  selector:
    app: syncthing
  ports:
  - name: syncthing
    protocol: TCP
    port: 8384
    targetPort: syncthing
---
apiVersion: v1
kind: Service
metadata:
  name: syncthing-cluster
  namespace: default
spec:
  selector:
    app: syncthing
  ports:
  - name: syncthing-tcp
    protocol: TCP
    port: 22000
    targetPort: 22000
  - name: syncthing-udp
    protocol: UDP
    port: 22000
    targetPort: 22000
  - name: syncthing-discovery
    protocol: UDP
    port: 21027
    targetPort: 21027
